[build]
  command = "npx prisma generate && npx prisma db push && npm run build"
  functions = "dist/netlify/functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/.prisma/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
